services:
  db_nest:
    image: mysql:8.0.30-debian
    container_name: mysql_nest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABADE=imersaonest
      - MYSQL_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
